This notebook loosely follows 04_extract_data_from_supplementary_excel_files.<br>It is a pure data-cleaning notebook.

Input: NIHMS687993-supplement-supp_data_4.xlsx was downloaded from [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4481139/).<br>Output: NIHMS687993-supplement-supp_data_4v2.csv

In [1]:
import pandas as pd
from functions.data import (cluster_markers_raw_df_to_tables,
                            cluster_markers_tables_to_df,
                            format_cluster_markers_datatypes)

In [2]:
to_save=True

# Get Data

In [3]:
cluster_markers_raw_df = pd.read_excel('data/downloads/NIHMS687993-supplement-supp_data_4.xlsx',
                                       sheet_name='FINAL_MARKERS_FOR_EACH_CLUSTER.',
                                       header=None, names=['gene_symbol', 'myAUC', 'myDiff', 'power', 'cluster_no'])
cluster_markers_raw_df = cluster_markers_raw_df.rename(columns={"Unnamed: 0": 'gene_symbol'})
print(cluster_markers_raw_df.shape)
cluster_markers_raw_df

(4296, 5)

      gene_symbol  myAUC     myDiff  power cluster_no
0             NaN    NaN        NaN    NaN        NaN
1             NaN    NaN        NaN    NaN        NaN
2     cluster no.      1  DE =  190    NaN        NaN
3             NaN  myAUC     myDiff  power  cluster #
4           CALB1  0.966   3.615047  0.466          1
...           ...    ...        ...    ...        ...
4291          PDC  0.163  -2.033191  0.337         39
4292        PDE6B  0.205  -2.102541  0.295         39
4293      RPGRIP1  0.221  -2.105338  0.279         39
4294          SAG  0.154  -2.197799  0.346         39
4295          RP1  0.197  -2.359118  0.303         39

[4296 rows x 5 columns]

# Clean Data

In [4]:
cluster_markers_tables = cluster_markers_raw_df_to_tables(cluster_markers_raw_df)
cluster_markers_df = cluster_markers_tables_to_df(cluster_markers_tables)
cluster_markers_df = format_cluster_markers_datatypes(cluster_markers_df)
cluster_markers_df

     gene_symbol  myAUC    myDiff  power  cluster_no
4          CALB1  0.966  3.615047  0.466           1
5         SLC4A3  0.963  3.448571  0.463           1
6           TPM3  0.965  3.151521  0.465           1
7          SEPT4  0.964  2.939258  0.464           1
8            VIM  0.944  2.937992  0.444           1
...          ...    ...       ...    ...         ...
4291         PDC  0.163 -2.033191  0.337          39
4292       PDE6B  0.205 -2.102541  0.295          39
4293     RPGRIP1  0.221 -2.105338  0.279          39
4294         SAG  0.154 -2.197799  0.346          39
4295         RP1  0.197 -2.359118  0.303          39

[4140 rows x 5 columns]

In [6]:
if to_save:
    cluster_markers_df.to_csv('data/NIHMS687993-supplement-supp_data_4v2.csv', index=None)