This notebook follows 05_make_rentina_subsets_for_teaching.

Input: differential_clusters_expression.csv

Output:
1. differential_clusters_lowrank.csv
2. differential_clusters_sparse.csv

In [1]:
import os
import pandas as pd
import r_pca

In [2]:
to_save=True

# Get Data

In [3]:
retina_clusters_expression_subset = pd.read_csv('data/retina/differential_clusters_expression.csv',
                                                index_col=0)
retina_clusters_expression_subset[['NRXN2', 'ATP1B1', 'PAX6', 'SLC32A1', 'SLC6A1', 'ELAVL3']]

                 NRXN2  ATP1B1  PAX6  SLC32A1  SLC6A1  ELAVL3
r1_GGCCGCAGTCCG   16.0   149.0   8.0      0.0     1.0    13.0
r1_CTTGTGCGGGAA   16.0   182.0  21.0      0.0    10.0     5.0
r1_GCGCAACTGCTC    7.0   119.0  10.0      0.0     5.0     4.0
r1_GATTGGGAGGCA   12.0    93.0   7.0      0.0     3.0     7.0
r1_GTGCCGCCTCTC    0.0     0.0   0.0      0.0     0.0     0.0
...                ...     ...   ...      ...     ...     ...
r1_CACCCAGTTTCG    0.0     0.0   0.0      0.0     0.0     0.0
r1_CCTGGAGAGTTT    0.0     0.0   0.0      0.0     0.0     0.0
r1_TCTTCACTCTTA    0.0     0.0   0.0      0.0     0.0     0.0
r1_GCCGTCTTACTA    0.0     0.0   0.0      0.0     0.0     0.0
r1_GACCAAACTAAT    0.0     0.0   1.0      0.0     0.0     0.0

[6020 rows x 6 columns]

# PCA

In [18]:
# Warning: this takes a long time...
smusher = r_pca.R_pca(retina_clusters_expression_subset.to_numpy())
%time lowrank, sparse = smusher.fit(max_iter=200)  # maybe change this to 105 to match Olga's notebook?
lowrank

iteration: 1, error: 0.6588671407509644
iteration: 100, error: 0.01123108356951265
iteration: 200, error: 0.01255636376305212
CPU times: user 29min 16s, sys: 52.7 s, total: 30min 8s
Wall time: 5min 16s

array([[-2.32822363e-06, -4.30369650e-07,  5.09947594e+00, ...,
         6.96435129e+00,  5.27273218e+01, -1.25831762e-10],
       [-4.46128176e-07,  3.93000013e-07,  9.00000003e+00, ...,
         4.99999976e+00,  6.39491305e+01,  9.63615235e-01],
       [-7.60151859e-07, -3.62638226e-07,  1.08803970e+01, ...,
         3.97061659e+00,  3.79249399e+01, -2.20913732e-07],
       ...,
       [-6.51058000e-06,  1.16562240e-01, -2.70136871e-07, ...,
         5.02277118e-07,  2.44506825e-07,  6.71133459e-07],
       [-1.78297067e-04,  2.83346428e-06,  5.21866852e-08, ...,
         5.30059728e-07, -7.39572174e-08,  1.14921914e-07],
       [-2.54761010e-04,  4.82610923e-06, -5.41799921e-08, ...,
        -3.82201832e-07,  9.60595969e-08, -4.51423669e-07]])

# Lowrank

In [5]:
lowrank_df = pd.DataFrame(lowrank,
                          index=retina_clusters_expression_subset.index,
                          columns=retina_clusters_expression_subset.columns)
lowrank_df.index.name = 'cell'
print(lowrank_df.shape)
lowrank_df.head()

(6020, 1270)

,1500015O10RIK,1500016L03RIK,1700025G04RIK,1810009A15RIK,1810037I17RIK,2010107E04RIK,2410066E13RIK,2610017I09RIK,2900011O08RIK,4833424O15RIK,...,ZFHX3,ZFHX4,ZFP365,ZFP36L1,ZFP804A,ZIC1,ZIC4,ZMAT4,ZWINT,ZYX
cell,,,,,,,,,,,,,,,,,,,,,
r1_GGCCGCAGTCCG,0.0,-0.0,-0.099476,0.0,0.000000,0.024608,0.000000,-0.003324,-0.000000,-0.000000,...,-0.000000,0.000000,0.024237,0.0,-0.000000,-0.000000,-0.000000,0.035649,0.272678,-0.000000
r1_CTTGTGCGGGAA,0.0,-0.0,0.000000,0.0,-0.000000,0.335530,0.000000,0.000000,0.122952,-0.037061,...,0.000000,0.007976,0.007178,0.0,-0.000000,0.000000,-0.000000,-0.000000,1.050869,0.036385
r1_GCGCAACTGCTC,0.0,0.0,0.119603,-0.0,-0.000000,0.103123,-0.044750,-0.000000,0.000000,-0.000000,...,-0.032961,-0.000000,-0.000000,-0.0,-0.000000,-0.000000,0.000000,0.029383,0.075060,-0.000000
r1_GATTGGGAGGCA,-0.0,-0.0,0.034560,0.0,0.145001,0.022376,0.250735,-0.000000,0.000000,-0.093518,...,0.079537,-0.026122,-0.000000,-0.0,-0.015459,0.110959,0.000000,-0.000000,-0.138410,-0.000000
r1_GTGCCGCCTCTC,-0.0,-0.0,0.032072,-0.0,-0.015275,0.112903,-0.151542,0.000000,-0.016578,-0.000000,...,-0.000000,-0.000000,0.086644,0.0,-0.000000,-0.009587,-0.000052,-0.000000,0.110131,-0.074799

In [7]:
if to_save:
    os.makedirs("data/pca", exist_ok=True)
    lowrank_df.to_csv('data/pca/differential_clusters_pca_lowrank.csv', index=True)

# Sparse

In [6]:
sparse_df = pd.DataFrame(sparse,
                         index=table1_diff_genes_cells.index,
                         columns=table1_diff_genes_cells.columns)
sparse_df.index.name = 'cell'
print(sparse_df.shape)
sparse_df.head()

(6020, 1270)

,1500015O10RIK,1500016L03RIK,1700025G04RIK,1810009A15RIK,1810037I17RIK,2010107E04RIK,2410066E13RIK,2610017I09RIK,2900011O08RIK,4833424O15RIK,...,ZFHX3,ZFHX4,ZFP365,ZFP36L1,ZFP804A,ZIC1,ZIC4,ZMAT4,ZWINT,ZYX
cell,,,,,,,,,,,,,,,,,,,,,
r1_GGCCGCAGTCCG,0.0,-0.0,-0.099476,0.0,0.000000,0.024608,0.000000,-0.003324,-0.000000,-0.000000,...,-0.000000,0.000000,0.024237,0.0,-0.000000,-0.000000,-0.000000,0.035649,0.272678,-0.000000
r1_CTTGTGCGGGAA,0.0,-0.0,0.000000,0.0,-0.000000,0.335530,0.000000,0.000000,0.122952,-0.037061,...,0.000000,0.007976,0.007178,0.0,-0.000000,0.000000,-0.000000,-0.000000,1.050869,0.036385
r1_GCGCAACTGCTC,0.0,0.0,0.119603,-0.0,-0.000000,0.103123,-0.044750,-0.000000,0.000000,-0.000000,...,-0.032961,-0.000000,-0.000000,-0.0,-0.000000,-0.000000,0.000000,0.029383,0.075060,-0.000000
r1_GATTGGGAGGCA,-0.0,-0.0,0.034560,0.0,0.145001,0.022376,0.250735,-0.000000,0.000000,-0.093518,...,0.079537,-0.026122,-0.000000,-0.0,-0.015459,0.110959,0.000000,-0.000000,-0.138410,-0.000000
r1_GTGCCGCCTCTC,-0.0,-0.0,0.032072,-0.0,-0.015275,0.112903,-0.151542,0.000000,-0.016578,-0.000000,...,-0.000000,-0.000000,0.086644,0.0,-0.000000,-0.009587,-0.000052,-0.000000,0.110131,-0.074799

In [8]:
if to_save:
    os.makedirs("data/pca", exist_ok=True)
    sparse_df.to_csv('data/pca/differential_clusters_pca_sparse.csv', index=True)